language: python
sudo: true
python:
  - "3.6"

cache:
  - pip

before_script:
  - pip install -e git+https://github.com/mobolic/facebook-sdk.git#egg=facebook-sdk
  - pip install selenium
  - pip install requests
  - pip install coverage
  - pip install codecov
  - pip install nose

script:
  - python pytest.py
  - nosetests -w / --with-coverage

after_success:
  - cat codecov.yml | curl --data-binary @- https://codecov.io/validate
  - codecov