language: python
sudo: true
python:
  - "3.6"

cache:
  - pip

before_script:
  - pip install --user git+https://github.com/mobolic/facebook-sdk.git#egg=facebook-sdk
  - pip install --user selenium
  - pip install --user requests
  - pip install --user coverage
  - pip install --user codecov
  - pip install --user nose

script:
  - python pytest.py
  - nosetests -v --cover-package=*.py —-with-coverage

after_success:
  - bash < (curl -s https://codecov.io/bash)