language: python
sudo: true
python:
  - "3.6"

cache:
  - pip

before_script:
  - pip install -e git+https://github.com/mobolic/facebook-sdk.git#egg=facebook-sdk
  - pip install selenium
  - pip install requests
  - pip install coverage
  - pip install codecov
  - pip install nose

script:
  - python pytest.py
  - python -m nose.core --tests "pytest.py" --cover-package=*.py --with-coverage $1

after_success:
  - bash < (curl -s https://codecov.io/bash)