language: python
python:
  - "3.6"

cache:
  - pip

before_script:
  - pip install -e git+https://github.com/mobolic/facebook-sdk.git#egg=facebook-sdk
  - pip install selenium
  - pip install requests
  - pip install coverage
  - pip install codecov
  
script:
  - coverage run pytest.py
  - codecov
  - python pytest.py

sudo: true

after_success:
  - codecov
  - bash < (curl -s https://codecov.io/bash)