language: python
python:
  - "3.6"

cache:
  - pip

before_script:
  - pip install -e git+https://github.com/mobolic/facebook-sdk.git#egg=facebook-sdk
  - pip install selenium
  - pip install requests
  - pip install coverage
  - pip install codecov
  - export CODECOV_TOKEN="a225c7c2-6b05-4677-b300-3c3e85a64699"

script:
  - python pytest.py
  - coverage run pytest.py

sudo: true

after_success:
  - codecov